name: Automation Task
description: Create a task for Claude Code to process automatically
title: "[Task]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Create an Automated Task

        This issue will be processed by Lazy_Birtd automation system.
        Provide detailed, step-by-step instructions for the best results.

        **Once created, add the `ready` label to start processing.**

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Brief overview of what needs to be done
      placeholder: "Add a health system to the player character that tracks health, handles damage, and emits signals."
    validations:
      required: true

  - type: textarea
    id: detailed_steps
    attributes:
      label: Detailed Steps
      description: Step-by-step instructions with file names, function names, and specific values
      placeholder: |
        1. Create res://player/health.gd
        2. Add Health class that extends Node
        3. Add @export var max_health: int = 100
        4. Add var current_health: int = max_health
        5. Implement func take_damage(amount: int) -> void
        6. Implement func heal(amount: int) -> void (max at max_health)
        7. Add signal health_changed(old_value: int, new_value: int)
        8. Emit health_changed in take_damage and heal methods
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know the task is complete?
      placeholder: |
        - [ ] Health class exists with all required methods
        - [ ] Tests pass (test_player_health.gd)
        - [ ] Signal emits correctly with old and new values
        - [ ] Health cannot go below 0 or above max_health
      value: |
        - [ ]
        - [ ] Tests pass
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Task Complexity
      description: How complex is this task? (affects resource allocation)
      options:
        - simple
        - medium
        - complex
      default: 1
    validations:
      required: true

  - type: input
    id: estimated_time
    attributes:
      label: Estimated Time
      description: How long do you expect this to take?
      placeholder: "30 minutes"

  - type: textarea
    id: context
    attributes:
      label: Context / References
      description: Links to docs, related issues, or additional context
      placeholder: |
        - Godot docs: https://docs.godotengine.org/en/stable/classes/class_node.html
        - Related to issue #41
        - See player.gd for integration example

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Anything else Claude should know?
      placeholder: "This is part of the combat system refactor. Make sure signals are compatible with the existing UI system."

  - type: markdown
    attributes:
      value: |
        ---

        ## Next Steps

        1. **Review** the task description - make sure steps are clear and specific
        2. **Create** the issue
        3. **Add `ready` label** to trigger automation
        4. **Monitor** progress with `./wizard.sh --status`
        5. **Review PR** when created (usually within 1-2 hours)

        **Tips for Better Results:**
        - ✅ Be specific (exact file names, function signatures)
        - ✅ Provide examples of expected behavior
        - ✅ Include test requirements
        - ✅ Reference existing code patterns
        - ❌ Avoid vague instructions ("make it better")
        - ❌ Don't assume Claude knows your project structure
